all:
	gcc -o stulag.buildrooms stulag.buildrooms.c
	gcc -o stulag.adventure stulag.adventure.c -lpthread

clean:
	@rm -rf *.o *.rooms.*
	@rm -f stulag.buildrooms
	@rm -f currentTime.txt
	@rm -f stulag.adventure
