all:
	gcc -g -o stulag.buildrooms stulag.buildrooms.c -lpthread
	gcc -g -o stulag.adventure stulag.adventure.c -lpthread

clean:
	@rm -rf *.o *.rooms.*
	@rm -f stulag.buildrooms
	@rm -f currentTime.txt
	@rm -f stulag.adventure
