all:
	gcc -g -o stulag.buildrooms stulag.buildrooms.c -lpthread
adventure:
	gcc -g -o stulag.adventure stulag.adventure.c -lpthread

clean:
	@rm -rf *.o *.rooms.*
	@rm stulag.buildrooms
	@rm stulag.adventure
